Author.destroy_all

Tag.destroy_all

Post.destroy_all

p "commencing seeding"
francisco = Author.create(username: "frantelope", bio:"I specialize in drawing people and trees, I also dabble in photography " , avatar_url: "")
netaly = Author.create(username: "nutella", bio: "I like coding, coding is fun, sometimes when I code I cry." , avatar_url:"")
maxwell = Author.create(username: "jaçie", bio: "Singer, songwriter. I also like to code on my free time." , avatar_url:"")
pablo = Author.create(username: "PabloNeruda", bio: "para que nadie sepa dónde, para que nadie entienda nada" , avatar_url:"")
barbara = Author.create(username: "YoItsBarbz", bio: "Yo, folk singer, water color artist, coder" , avatar_url:"")
karem = Author.create(username: "teflon", bio: "singer in the shower, coder, i collect mugs and tea" , avatar_url:"")
donat = Author.create(username: "donut", bio: "let me explain! I love art, I'm very pasionate about art... Sting is a big hero of mine." , avatar_url:"")
p "seeded users"
tag1 = Tag.create(name: "acrylic", likes: "5")
tag2 = Tag.create(name: "oil", likes: "8")
tag3 = Tag.create(name: "drawing", likes: "5")
tag5 = Tag.create(name: "photography", likes: "5")
tag6 = Tag.create(name: "music", likes: "5")
tag7 = Tag.create(name: "poetry", likes: "5")
p "seeded tags"
#TODO add art and reseed
art1 = Post.create(title: "Love Lost", image_url:"https://d2jv9003bew7ag.cloudfront.net/uploads/Parra-Love-lost-2016.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art2 = Post.create(title: "Salute 2", image_url:"https://www.we-heart.com/upload-images/parrasalut2@2x.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art3 = Post.create(title: "Salute Sculpture", image_url:"https://www.we-heart.com/upload-images/parrasalut1753.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art4 = Post.create(title: "The Fall", image_url:"https://weandthecolor.com/wp-content/uploads/2016/05/The-Fall-2014-%E2%80%93-Painting-by-Danish-artist-Piet-Parra-created-with-acrylic-on-canvas-100-x-100-cm-39.37-x-39.37-in.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art5 = Post.create(title: "Love Lost", image_url:"https://d2jv9003bew7ag.cloudfront.net/uploads/Parra-Love-lost-2016.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art6 = Post.create(title: "Salute 2", image_url:"https://www.we-heart.com/upload-images/parrasalut2@2x.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art7 = Post.create(title: "Salute Sculpture", image_url:"https://www.we-heart.com/upload-images/parrasalut1753.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art8 = Post.create(title: "The Fall", image_url:"https://weandthecolor.com/wp-content/uploads/2016/05/The-Fall-2014-%E2%80%93-Painting-by-Danish-artist-Piet-Parra-created-with-acrylic-on-canvas-100-x-100-cm-39.37-x-39.37-in.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art9 = Post.create(title: "Love Lost", image_url:"https://d2jv9003bew7ag.cloudfront.net/uploads/Parra-Love-lost-2016.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art10 = Post.create(title: "Salute 2", image_url:"https://www.we-heart.com/upload-images/parrasalut2@2x.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art11 = Post.create(title: "Salute Sculpture", image_url:"https://www.we-heart.com/upload-images/parrasalut1753.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art12 = Post.create(title: "The Fall", image_url:"https://weandthecolor.com/wp-content/uploads/2016/05/The-Fall-2014-%E2%80%93-Painting-by-Danish-artist-Piet-Parra-created-with-acrylic-on-canvas-100-x-100-cm-39.37-x-39.37-in.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art13 = Post.create(title: "Love Lost", image_url:"https://d2jv9003bew7ag.cloudfront.net/uploads/Parra-Love-lost-2016.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art14 = Post.create(title: "Salute 2", image_url:"https://www.we-heart.com/upload-images/parrasalut2@2x.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art15 = Post.create(title: "Salute Sculpture", image_url:"https://www.we-heart.com/upload-images/parrasalut1753.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art16 = Post.create(title: "The Fall", image_url:"https://weandthecolor.com/wp-content/uploads/2016/05/The-Fall-2014-%E2%80%93-Painting-by-Danish-artist-Piet-Parra-created-with-acrylic-on-canvas-100-x-100-cm-39.37-x-39.37-in.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art17 = Post.create(title: "Love Lost", image_url:"https://d2jv9003bew7ag.cloudfront.net/uploads/Parra-Love-lost-2016.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art18 = Post.create(title: "Salute 2", image_url:"https://www.we-heart.com/upload-images/parrasalut2@2x.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art19 = Post.create(title: "Salute Sculpture", image_url:"https://www.we-heart.com/upload-images/parrasalut1753.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art20 = Post.create(title: "The Fall", image_url:"https://weandthecolor.com/wp-content/uploads/2016/05/The-Fall-2014-%E2%80%93-Painting-by-Danish-artist-Piet-Parra-created-with-acrylic-on-canvas-100-x-100-cm-39.37-x-39.37-in.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art21 = Post.create(title: "Love Lost", image_url:"https://d2jv9003bew7ag.cloudfront.net/uploads/Parra-Love-lost-2016.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art22 = Post.create(title: "Salute 2", image_url:"https://www.we-heart.com/upload-images/parrasalut2@2x.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art23 = Post.create(title: "Salute Sculpture", image_url:"https://www.we-heart.com/upload-images/parrasalut1753.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art24 = Post.create(title: "The Fall", image_url:"https://weandthecolor.com/wp-content/uploads/2016/05/The-Fall-2014-%E2%80%93-Painting-by-Danish-artist-Piet-Parra-created-with-acrylic-on-canvas-100-x-100-cm-39.37-x-39.37-in.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art25 = Post.create(title: "Love Lost", image_url:"https://d2jv9003bew7ag.cloudfront.net/uploads/Parra-Love-lost-2016.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art26 = Post.create(title: "Salute 2", image_url:"https://www.we-heart.com/upload-images/parrasalut2@2x.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art27 = Post.create(title: "Salute Sculpture", image_url:"https://www.we-heart.com/upload-images/parrasalut1753.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art28 = Post.create(title: "The Fall", image_url:"https://weandthecolor.com/wp-content/uploads/2016/05/The-Fall-2014-%E2%80%93-Painting-by-Danish-artist-Piet-Parra-created-with-acrylic-on-canvas-100-x-100-cm-39.37-x-39.37-in.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art29 = Post.create(title: "Love Lost", image_url:"https://d2jv9003bew7ag.cloudfront.net/uploads/Parra-Love-lost-2016.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art30 = Post.create(title: "Salute 2", image_url:"https://www.we-heart.com/upload-images/parrasalut2@2x.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art31 = Post.create(title: "Salute Sculpture", image_url:"https://www.we-heart.com/upload-images/parrasalut1753.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art32 = Post.create(title: "The Fall", image_url:"https://weandthecolor.com/wp-content/uploads/2016/05/The-Fall-2014-%E2%80%93-Painting-by-Danish-artist-Piet-Parra-created-with-acrylic-on-canvas-100-x-100-cm-39.37-x-39.37-in.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art33 = Post.create(title: "Love Lost", image_url:"https://d2jv9003bew7ag.cloudfront.net/uploads/Parra-Love-lost-2016.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art34 = Post.create(title: "Salute 2", image_url:"https://www.we-heart.com/upload-images/parrasalut2@2x.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art35 = Post.create(title: "Salute Sculpture", image_url:"https://www.we-heart.com/upload-images/parrasalut1753.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art36 = Post.create(title: "The Fall", image_url:"https://weandthecolor.com/wp-content/uploads/2016/05/The-Fall-2014-%E2%80%93-Painting-by-Danish-artist-Piet-Parra-created-with-acrylic-on-canvas-100-x-100-cm-39.37-x-39.37-in.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art37 = Post.create(title: "Love Lost", image_url:"https://d2jv9003bew7ag.cloudfront.net/uploads/Parra-Love-lost-2016.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art38 = Post.create(title: "Salute 2", image_url:"https://www.we-heart.com/upload-images/parrasalut2@2x.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art39 = Post.create(title: "Salute Sculpture", image_url:"https://www.we-heart.com/upload-images/parrasalut1753.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art40 = Post.create(title: "The Fall", image_url:"https://weandthecolor.com/wp-content/uploads/2016/05/The-Fall-2014-%E2%80%93-Painting-by-Danish-artist-Piet-Parra-created-with-acrylic-on-canvas-100-x-100-cm-39.37-x-39.37-in.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art42 = Post.create(title: "Love Lost", image_url:"https://d2jv9003bew7ag.cloudfront.net/uploads/Parra-Love-lost-2016.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art43 = Post.create(title: "Salute 2", image_url:"https://www.we-heart.com/upload-images/parrasalut2@2x.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art44 = Post.create(title: "Salute Sculpture", image_url:"https://www.we-heart.com/upload-images/parrasalut1753.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art45 = Post.create(title: "The Fall", image_url:"https://weandthecolor.com/wp-content/uploads/2016/05/The-Fall-2014-%E2%80%93-Painting-by-Danish-artist-Piet-Parra-created-with-acrylic-on-canvas-100-x-100-cm-39.37-x-39.37-in.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art46 = Post.create(title: "Love Lost", image_url:"https://d2jv9003bew7ag.cloudfront.net/uploads/Parra-Love-lost-2016.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art47 = Post.create(title: "Salute 2", image_url:"https://www.we-heart.com/upload-images/parrasalut2@2x.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art49 = Post.create(title: "Salute Sculpture", image_url:"https://www.we-heart.com/upload-images/parrasalut1753.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art50 = Post.create(title: "The Fall", image_url:"https://weandthecolor.com/wp-content/uploads/2016/05/The-Fall-2014-%E2%80%93-Painting-by-Danish-artist-Piet-Parra-created-with-acrylic-on-canvas-100-x-100-cm-39.37-x-39.37-in.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art51 = Post.create(title: "Love Lost", image_url:"https://d2jv9003bew7ag.cloudfront.net/uploads/Parra-Love-lost-2016.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art52 = Post.create(title: "Salute 2", image_url:"https://www.we-heart.com/upload-images/parrasalut2@2x.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art53 = Post.create(title: "Salute Sculpture", image_url:"https://www.we-heart.com/upload-images/parrasalut1753.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art54 = Post.create(title: "The Fall", image_url:"https://weandthecolor.com/wp-content/uploads/2016/05/The-Fall-2014-%E2%80%93-Painting-by-Danish-artist-Piet-Parra-created-with-acrylic-on-canvas-100-x-100-cm-39.37-x-39.37-in.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art55 = Post.create(title: "Love Lost", image_url:"https://d2jv9003bew7ag.cloudfront.net/uploads/Parra-Love-lost-2016.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art56 = Post.create(title: "Salute 2", image_url:"https://www.we-heart.com/upload-images/parrasalut2@2x.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art57 = Post.create(title: "Salute Sculpture", image_url:"https://www.we-heart.com/upload-images/parrasalut1753.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art58 = Post.create(title: "The Fall", image_url:"https://weandthecolor.com/wp-content/uploads/2016/05/The-Fall-2014-%E2%80%93-Painting-by-Danish-artist-Piet-Parra-created-with-acrylic-on-canvas-100-x-100-cm-39.37-x-39.37-in.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art59 = Post.create(title: "Love Lost", image_url:"https://d2jv9003bew7ag.cloudfront.net/uploads/Parra-Love-lost-2016.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art60 = Post.create(title: "Salute 2", image_url:"https://www.we-heart.com/upload-images/parrasalut2@2x.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art61 = Post.create(title: "Salute Sculpture", image_url:"https://www.we-heart.com/upload-images/parrasalut1753.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art62 = Post.create(title: "The Fall", image_url:"https://weandthecolor.com/wp-content/uploads/2016/05/The-Fall-2014-%E2%80%93-Painting-by-Danish-artist-Piet-Parra-created-with-acrylic-on-canvas-100-x-100-cm-39.37-x-39.37-in.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art63 = Post.create(title: "Love Lost", image_url:"https://d2jv9003bew7ag.cloudfront.net/uploads/Parra-Love-lost-2016.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art64 = Post.create(title: "Salute 2", image_url:"https://www.we-heart.com/upload-images/parrasalut2@2x.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art65 = Post.create(title: "Salute Sculpture", image_url:"https://www.we-heart.com/upload-images/parrasalut1753.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art66 = Post.create(title: "The Fall", image_url:"https://weandthecolor.com/wp-content/uploads/2016/05/The-Fall-2014-%E2%80%93-Painting-by-Danish-artist-Piet-Parra-created-with-acrylic-on-canvas-100-x-100-cm-39.37-x-39.37-in.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art67 = Post.create(title: "Love Lost", image_url:"https://d2jv9003bew7ag.cloudfront.net/uploads/Parra-Love-lost-2016.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art68 = Post.create(title: "Salute 2", image_url:"https://www.we-heart.com/upload-images/parrasalut2@2x.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art69 = Post.create(title: "Salute Sculpture", image_url:"https://www.we-heart.com/upload-images/parrasalut1753.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art70 = Post.create(title: "The Fall", image_url:"https://weandthecolor.com/wp-content/uploads/2016/05/The-Fall-2014-%E2%80%93-Painting-by-Danish-artist-Piet-Parra-created-with-acrylic-on-canvas-100-x-100-cm-39.37-x-39.37-in.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art71 = Post.create(title: "Love Lost", image_url:"https://d2jv9003bew7ag.cloudfront.net/uploads/Parra-Love-lost-2016.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art72 = Post.create(title: "Salute 2", image_url:"https://www.we-heart.com/upload-images/parrasalut2@2x.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art73 = Post.create(title: "Salute Sculpture", image_url:"https://www.we-heart.com/upload-images/parrasalut1753.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art74 = Post.create(title: "El Eric", image_url:"https://i.ibb.co/rfZfkB2/20200811-105611.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art75 = Post.create(title: "El Eric", image_url:"https://i.ibb.co/rfZfkB2/20200811-105611.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art76 = Post.create(title: "El Eric", image_url:"https://i.ibb.co/rfZfkB2/20200811-105611.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art77 = Post.create(title: "El Eric", image_url:"https://i.ibb.co/rfZfkB2/20200811-105611.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art78 = Post.create(title: "El Eric", image_url:"https://i.ibb.co/rfZfkB2/20200811-105611.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art79 = Post.create(title: "El Eric", image_url:"https://i.ibb.co/rfZfkB2/20200811-105611.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art80 = Post.create(title: "El Eric", image_url:"https://i.ibb.co/rfZfkB2/20200811-105611.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)
art81 = Post.create(title: "El Eric", image_url:"https://i.ibb.co/rfZfkB2/20200811-105611.jpg", author_id: Author.all.sample.id, tag_id: Tag.all.sample.id)

p "seeded posts"